from selenium.webdriver.common.by import By


class ShoppingCartPageLocators(object):
    checkout_button = By.XPATH, "//a[contains(text(),'Checkout')]"
    checkout_title = By.XPATH, "//h1[contains(text(),'Checkout')]"
    register_account_radio_button = By.XPATH, "//input[@value='register']"
    continue_registration_account_button = By.ID, "button-account"
    first_name_field = By.ID, "input-payment-firstname"
    lastname_name_field = By.ID, "input-payment-lastname"
    email_field = By.ID, "input-payment-email"
    telephone_field = By.ID, "input-payment-telephone"
    address_1_field = By.ID, "input-payment-address-1"
    city_field = By.ID, "input-payment-city"
    postcode_field = By.ID, "input-payment-postcode"
    password_field = By.ID, "input-payment-password"
    password_confirm_field = By.ID, "input-payment-confirm"
    country_field = By.ID, "input-payment-country"
    region_state_field = By.ID, "input-payment-zone"
    privacy_policy_checkbox = By.XPATH, "//input[@name='agree']"
    continue_registration_button = By.ID, "button-register"
    remove_from_shopping_cart_button = By.XPATH, "//button[@data-original-title='Remove']"
    quantity_field = By.XPATH, "//input[@size='1']"
    update_quantity_button = By.XPATH, "//button[@data-original-title='Update']"
    shipping_taxes_section = By.XPATH, "//a[contains(text(),'Estimate Shipping & Taxes')]"
    shipping_taxes_country_field = By.ID, "input-country"
    shipping_taxes_region_state_field = By.ID, "input-zone"
    shipping_taxes_postcode_field = By.ID, "input-postcode"
    get_quotes_button = By.XPATH, "//button[contains(text(),'Get Quotes')]"
    cancel_button = By.XPATH, "//button[contains(text(),'Cancel')]"
    billing_continue_button = By.ID, "button-payment-address"
    delivery_continue_button = By.ID, "button-shipping-address"
    delivery_method_comment = By.XPATH, "//textarea[@name='comment']"
    delivery_method_continue_button = By.ID, "button-shipping-method"
    terms_conditions_checkbox = By.XPATH, "//input[@name='agree']"
    payment_continue_button = By.ID, "button-payment-method"
    confirm_order = By.ID, "button-confirm"
    success_alert = By.XPATH, "//div[contains(text(),'Success')]"
    continue_button = By.XPATH, "//a[contains(text(),'Continue')]"
